drive_root: /content/drive/MyDrive/adverse_weather_project
project: /content/drive/MyDrive/adverse_weather_project/runs

datasets:
  bdd: /content/bdd100k_6cls_yolo/dataset.yaml
  dawn: /content/dawn_6cls_yolo/dataset.yaml

