defaults: configs/common/train_defaults.yaml
paths: configs/common/paths_colab.yaml

model: fasterrcnn_resnet50_fpn
weights: COCO_V1
dataset: bdd
name: stage1_bdd_faster_rcnn

epochs: 30
batch: 4
optimizer: SGD
lr0: 0.005
momentum: 0.9
num_classes: 7
